name: Sample GitHub Job
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature1
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event Detected: ${{ github.event_name }}"
  Job2-Windows:
    runs-on: windows-latest
    steps:
      - run: echo "Event Detected: ${{ github.event_name }}"
